// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJE8rq9qWjq5cEGNaj0S4wX2KafBLrCU',
    appId: '1:413516947682:web:9a95c746e52cce4f637ebb',
    messagingSenderId: '413516947682',
    projectId: 'pilar-app-test',
    authDomain: 'pilar-app-test.firebaseapp.com',
    storageBucket: 'pilar-app-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7EAxamHd6zixjwplXtO9D8YhOHCZQFg',
    appId: '1:413516947682:android:4e01e30e2b6c2ab6637ebb',
    messagingSenderId: '413516947682',
    projectId: 'pilar-app-test',
    storageBucket: 'pilar-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkXfoH9pm19eVqf9eYKiavUIcipsz9Ym4',
    appId: '1:413516947682:ios:2fed0767c1f0d828637ebb',
    messagingSenderId: '413516947682',
    projectId: 'pilar-app-test',
    storageBucket: 'pilar-app-test.appspot.com',
    iosClientId: '413516947682-ge0f7mt5picbkqnqr06o068ojqpuk4pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkXfoH9pm19eVqf9eYKiavUIcipsz9Ym4',
    appId: '1:413516947682:ios:2fed0767c1f0d828637ebb',
    messagingSenderId: '413516947682',
    projectId: 'pilar-app-test',
    storageBucket: 'pilar-app-test.appspot.com',
    iosClientId: '413516947682-ge0f7mt5picbkqnqr06o068ojqpuk4pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
